theme: jekyll-theme-minimal
title: "Will Lockhart"
logo: /images/IMG_6281.jpg
description: "Postdoctoral Fellow at the Institute on the Environment (IonE) @ University of Minnesota. 
Research scientist in sustainability, astrophysicist, 
and director of the first feature documentary on the game of Go. <br /> <br /> You can reach me at wlock@umn.edu."
